language: objective-c
osx_image: xcode7.3
script: xcodebuild -project Stargate.xcodeproj -scheme StargateTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' -enableCodeCoverage YES test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
